### ISSUE TITLE
Feature Request: Logistics Pipes integration

### ISSUE THREAD

**Issue by TomeWyrm** [Mordenkainen/EquivalentEnergistics#10]
Pretty much what the title says, some method of allowing this mod to be used with Logistics Pipes autocrafting. As it is, you can technically do this with pure Project E and Logistics Pipes via use of suppliers/providers and condensers... that particular method is very brute-force, inelegant, and prone to breakage.

My initial idea is single-recipe patterns. Because LP is unlikely to appreciate the way AE assemblers work :-)

**Comment by Mordenkainen** [comment]
So I have looked at the LP code, and it seems like it would be VERY hard to implement the level of integration I would want.

I will get in touch with the authors to see if there is anything I can do, but at this point I'm not sure it's possible.

**Comment by Mordenkainen** [comment]
OK, so here is my idea for making this happen:

1. Make a block which when loaded with a "pattern" acts as an automatic crafting table for EMC Crystals > a particular item. Crystals pumped in to any side = output item that can be pumped out any side. Excess crystals may also be pumped out any side.
2. Create a pattern item. This item, when crafted together with any block/item with an EMC value, by a player who has transmutation for this block/item unlocked, becomes a pattern that can be loaded into the table above to identify the target item.
3. Add another block that will convert items to EMC Crystals for the cost of RF or LP power (or no power, it would be configurable).

These changes will provide sort of a "starter tier" of the EMC Autocrafting, that a user could use with pipes, hoppers, etc. In addition, it would be able to interface with an LP crafting pipe. In fact, it should allow the system to work with just about any automated crafting system to some extent.

Does this seem like a workable solution?

**Comment by TomeWyrm** [comment]
That looks like it would work beautifully from a player and pack maker perspective.

**Comment by Mordenkainen** [comment]
Closing this issue. I have opened several issues and milestones to cover the work required to accomplish this request. Progress on this will be tracked through those.
