### ISSUE TITLE
when refined storage 1.6 is released, remove support for refined storage or implement your own projecte support for refined storage

### ISSUE THREAD

**Issue by escman1999** [Mordenkainen/EquivalentEnergistics#115]
when refined storage 1.6 is released, all current projecte support (external storage showing everything inside the transmutation table, emc values for projecte items, and emc values showing up inside the refined storage grid gui) will be removed, thus, the refined storage aspect of this mod will no longer function, unless you add your own full projecte support

**Comment by Mordenkainen** [comment]
Huh?

What Refined Storage aspect?

This mod directly uses the ProjectE API and does not interact with RS at all.

**Comment by escman1999** [comment]
ah, my bad then
