### ISSUE TITLE
Trying to pump items into the EMC condenser crashes game/server and corrupts world save

### ISSUE THREAD

**Issue by ghost** [Mordenkainen/EquivalentEnergistics#116]
When trying to pump an item into the EMC condenser, the world save is broken and the world can no longer be loaded. I tried via hoppers and also itemducts from Thermal Expansion and had the same result. There was a valid ME system with EMC storage available in both cases.

**Comment by Mordenkainen** [comment]
Crashlog? Version of mod? Etc?

Anything?

**Comment by ghost** [comment]
Don't have a crash log sorry but you can recreate it easily (I did it many times). As for the version, its the 1.12 Minecraft version in the latest version of Foolcraft 3 (should have included that in the original sorry also.

**Comment by Mordenkainen** [comment]
I can not recreate it easily. Had this issue been prevalent, the mod would not have been released.

I really could use a crashlog, but if you can at least provide the versions of ProjectE and EqE. I know you said it is the 1.12 ver, but there are two of those so I need to know which one.

Also, if your PE version is 1.3.1B that is your problem. They recently made a change that breaks all addons. Until I can fix that, downgrade to the 1.3.1 version. See issue #98.

**Comment by ghost** [comment]
Equivalent Energistics is version 0.8.1
But also projects is version 1.3.1B so yeah that must be the problem.
Thanks for the info though
