### ISSUE TITLE
[Question] Does this mod work with ProjectE 1.3.0, or 1.3.1?  

### ISSUE THREAD

**Issue by HydrogenC** [Mordenkainen/EquivalentEnergistics#123]
The APIs changed in ProjectE 1.3.1, so a mod cannot be both compatiable with both ProjectE PE1.3.0 and PE1.3.1B. So which version does this mod support?

**Comment by Mordenkainen** [comment]
Currently 1.3.0... 

See issue #98

**Comment by HydrogenC** [comment]
OK

**Comment by HydrogenC** [comment]
When would this mod support 1.3.1 because other ProjectE addons require 1.3.1
