### ISSUE TITLE
AbstractMethodError when using EMC cell with AE2 storage cell in the same drive

### ISSUE THREAD

**Issue by arketec** [Mordenkainen/EquivalentEnergistics#126]
crash report: https://pastebin.com/vWZjBSn5

mod version: 1.12.2-0.8.2 
ae2 version: rv6-alpha-3 
projecte version: 1.12.2-PE1.3.0

crash occured in method com.mordenkainen.equivalentenergistics.items.ItemEMCCell.getCellInventory

This crash puts the server into a reboot cycle,

**Comment by arketec** [comment]
this might be related to [98](https://github.com/Mordenkainen/EquivalentEnergistics/issues/98), but I thought that was only an issue with PE1.3.1?

**Comment by arketec** [comment]
I forgot to include the steps to reproduce:

1) Attach an EMC Condenser and an EMC assembler to an ME network with crafting cpus
2) install EMC storage cell in an ME Drive
3) install ME storage cell in an ME Drive ----> crash here

**Comment by arketec** [comment]
upon further testing, it seems only step
 3) install ME storage cell in an ME Drive 
from above is required to reproduce the crash

**Comment by Mordenkainen** [comment]
AE2 RV6 is an Alpha build. Not many addons suppprt it, incliding this one.

Once it goes to beta, support will be added.

**Comment by arketec** [comment]
ok thanks for the update
