### ISSUE TITLE
crash when tome is in assembler, tome, and me system

### ISSUE THREAD

**Issue by r3b3lxxleader** [Mordenkainen/EquivalentEnergistics#127]
https://pastebin.com/qr2ysAZ5

I've had this happen at least twice that I know of once in a single player world where the guy said it corrupted the world when he had a tome in the assembler and tried to access the me and once server side which I don't know what was going on there that caused it but the crash log from the server is the link.

**Comment by Mordenkainen** [comment]
Issue #98
