### ISSUE TITLE
[1.12.2]Servercrash Autocrafting

### ISSUE THREAD

**Issue by ghost** [Mordenkainen/EquivalentEnergistics#128]
https://paste.myftb.de/ajugesonez

EquivalentEnergistics: 0.8.2
ProjectE: PE1.3.1B
appliedenergistics2: rv5-stable-11

**Comment by MaPePeR** [comment]
EquivalentEnergistics is not yet compatible with ProjectE 1.3.1B. Downgrade ProjectE.

**Comment by Mordenkainen** [comment]
Dupe of #98
