### ISSUE TITLE
Massive Power Requirements

### ISSUE THREAD

**Issue by smartsoldier** [Mordenkainen/EquivalentEnergistics#132]
I dropped this mod into the recent StoneBlock modpack and I'm trying to get massive amounts of EMC into this system really quickly. I am condensing items worth 1+ million EMC each and the condenser keeps running out of power. I have plenty of power going straight into my AE system but it isn't enough. Is there some kind of throughput problem? Can I power the thing externally?

**Comment by Mordenkainen** [comment]
Sort of...

The condenser isn't running out of power, your AE network is.

AE has a limit to the default amount of power a network can store (the amount depends on how many controller blocks the network has).

If you need more power than the network can hold, you get this.

The solution is to add energy cells.
