### ISSUE TITLE
the EMC condenser doesnt read from an SSD

### ISSUE THREAD

**Issue by Algester** [Mordenkainen/EquivalentEnergistics#133]
if I make a Super Soaryn Drive IE making a tiered subnet the EMC condenser doesnt seem to read that there is an active EMC drive in the system and thus can't be fed EMC unless I manually feed it dense crystals or charge the drive via energy or anti-matter machines

current version is
Equivalent Energistics 1.12.2 PE 1.3.1B

**Comment by Mordenkainen** [comment]
This is not a bug. SSDs use interface/storage bus combos to share items from subnetworks. EMC is not an item, so does not get shared through the interface.

**Comment by Algester** [comment]
I see nothing too big of a problem I guess
