### ISSUE TITLE
emc condensers cannot process an item in multiple ticks

### ISSUE THREAD

**Issue by ghost** [Mordenkainen/EquivalentEnergistics#134]
https://github.com/Mordenkainen/EquivalentEnergistics/issues/22
May be related, may not be related.

Forge: 2768
AE: rv6-stable-4
This mod: 0.8.3
https://hastebin.com/asuwahilon.coffeescript

I have enough energy. The operation that I'm attempting would take 22,589.11 AE at current settings. I have 9 dense energy cells at 1.6 M AE a piece.
I have room for the stuff to go (4 tier 6 EMC cells at 1.024B each in the system).
Everything is connected right as items with a lower EMC value (such as coal blocks, improved EMC condensers, and other things with sane EMC per item work.
The item in question has ~2 Mil EMC.
There are no errors on the server, sadly
I do have inequivalent exchange set, however it isn't causing issues with items with a lower emc value. I figured I'd mention it anyway in case there's a known conflict.

If this setup looks derp, it's because it is. This is a testing world where I do weird things to try to find bugs.

![2018-12-09_23 05 41](https://user-images.githubusercontent.com/17183816/49710383-00037f80-fc07-11e8-935d-2b7f2530a34b.png)

**Comment by Mordenkainen** [comment]
It sounds like your network meets all the requirements for the item.

Couple of questions:
- What tier of condenser? Based on you config your condensers would have limits of 20,000; 200,000; 2,000,000, Unlimited. So a > 2,000,000 item requires an Ultimate condenser.
- Are you using any kind of power scaling in AE? This would be configured in AEs settings.

Do you have Hwyla? The red corners on the condenser say it has an error. Hwyla would tell you what that error is.

**Comment by ghost** [comment]
It's not actually red, it's dark orange, and I caught it at a bad time. The fancy AE color effects don't sync well between mods. For the record though, I use theoneprobe as it's more efficient.

I'm using the improved one. I have been under the assumption that the way it would handle large items would be to hold it in queue, convert x amount per tick, and keep doing that until you reach the value of the item. If it truly cannot convert an item larger than it's per tick rate then they are going to clog very easily late game as I have items with over 35 mil EMC in the pack.
If this is the case, maybe it would be a good idea to have the item not be able to go in so it can pass through to the next machine/storage/etc... that the item can actually be processed by.

Assuming you're talking about within AE itself, then no. I have however changed the default RF to AE rate as part of a broad RF squish in the pack. I doubt this is related, but I figured I'd mention it.

**Comment by Mordenkainen** [comment]
TOP works as well 

Yes, the condenser will not "partially" convert an item. Either it can convert it in one operation or it cannot.

If you need to convert extremely high EMC value items, that is what the ultimate condenser is for.

**Comment by ghost** [comment]
Alright, that's what I thought the holdup was. In that case, I would like to suggest that if the item cannot be converted it gets rejected (as above).

**Comment by Mordenkainen** [comment]
The first two tiers of condensers do reject items that are too large. The top two tier have the ability to export uncondensable items to an adjacent inventory. This was requested by users so that the condenser could be used to sort items with emc from those without.

**Comment by ghost** [comment]
Wait they do? And here I've been using a complex conduit setup to prioritize items to condensers and then have an interface at the end with 0 (lowest) priority. -makes a note to change my setups-
