### ISSUE TITLE
Mod Breaks the game when combinded with these mods...

### ISSUE THREAD

**Issue by PitchBlackLaser** [Mordenkainen/EquivalentEnergistics#143]
Your version EquivalentEnergistics-1.12.2-PE_1.3.1B-AE2_RV6-0.8.3.jar seems to have a compatibility issue with one or multiple of my mods.

The Game loads up and I can start a map but the map won't load...
it won't crash either.... after a while it stops loading... but the loading screen is still there...

those are my mods... so you can recreate the issue on your end possibly
https://imgur.com/a/RyR5efl

PS: your mod is amazing... I would really love to use it... but not if it means parting from the other mods I have.

**Comment by Mordenkainen** [comment]
The quality of that picture is too low for me to read what mods are there. If you could find another way to provide your mod list it would be great.

**Comment by Mordenkainen** [comment]
Ok, now that I have looked again... You have PE 1.4.1. It is not compatible at this time.

**Comment by Xnosis** [comment]
It's actually a combo of this mod and ProjectE Integration that causes the problem.

https://pastebin.com/7z9aBWMB

EE and PE (1.4.1) load just fine on their own. Same with PEi and PE (latest versions). It is only when combined here that it doesn't load the game.

**Comment by IZeeLikeEyeZee** [comment]
> Ok, now that I have looked again... You have PE 1.4.1. It is not compatible at this time.

When will it be compatible?
I also would really like to use your mod, so please let me know, thanks!

**Comment by auddie2015** [comment]
Scratch that. If you have Equivalent Integrations installed, it's book of Knowledge crashes the game with this installed. I know how to resolve that, which involves taking all of my EMC out of it and disabling the mod. This one is better because it doesn't need reset every time you start the game because it doesn't forget your knowledge.

**Comment by Mordenkainen** [comment]
C6.oeuui
Y

**Comment by ghost** [comment]
Scratch that it's projecte in particular when you use this mod with it it just crashes and also creates crashes from other mods.

**Comment by Mordenkainen** [comment]
Closing. Issue tracked under #140
