### ISSUE TITLE
Pending Pull Request?

### ISSUE THREAD

**Issue by Joly0** [Mordenkainen/EquivalentEnergistics#146]
Hey, just wanted to ask, what about the pending pull request to fix equivalent energistics for projecte 1.4.1? Is this pull accepted anytime soon? Would be really happy to see that

**Comment by Mordenkainen** [comment]
The pull request is incomplete. At best existing users upgrading will lose a significant amount of stored EMC. (999 EMC lost out of every 1000 stored). And the server will crash as soon as certain features are accessed.

The pull request, as well as the remaining changes are being done as well as several major performance optimizations. These changes are currently in-test on 1.12.2, and assuming no major issues are found, should be released in the near future.

**Comment by ElektroKill** [comment]
Any Progress on support for ProjectE 1.4.1 ?

**Comment by ghost** [comment]
I legit need this

**Comment by Mordenkainen** [comment]
Closing. Issue tracked under #140
