### ISSUE TITLE
Crash while hovering in ME Drive

### ISSUE THREAD

**Issue by kingOlegos** [Mordenkainen/EquivalentEnergistics#148]
I can access my ME Drive, but when I hover over the EMC Storage Module the game instantly crashes.

[crash-2020-02-23_22.38.16-client.txt](https://github.com/Mordenkainen/EquivalentEnergistics/files/4243355/crash-2020-02-23_22.38.16-client.txt)

I will gladly answer questions to help this WONDERFUL mod!

**Comment by Mordenkainen** [comment]
Not compat with PE V 1.4 or higher.
