### ISSUE TITLE
[1.12.2] Crash on server

### ISSUE THREAD

**Issue by lsk-china** [Mordenkainen/EquivalentEnergistics#157]
### Env: 
- Forge: forge-1.12.2-14.23.5.2860
- EquivalentEnergistics: PE_1.3.1B-AE2_RV6-0.8.3
- Appeng: appliedenergistics2-rv6-stable-7
- java: 1.8.0_362
- ProjectE: PE1.4.1
- ProjectEX: 1.2.0.40
### Issue
  Server crashes when I let my Arcane Transmutation Tablet (from ProjectEX) learn the final star (from ProjectEX).
  Full log available in attachment.
(Maybe another client-only class or my copy is outdated?)

[crash-2023-02-10_21.07.51-server.txt](https://github.com/Mordenkainen/EquivalentEnergistics/files/10707703/crash-2023-02-10_21.07.51-server.txt)
[latest.log](https://github.com/Mordenkainen/EquivalentEnergistics/files/10707712/latest.log)

**Comment by Mordenkainen** [comment]
EquivalentEnergistics: **PE_1.3.1B**-AE2_RV6-0.8.3
ProjectE: **PE1.4.1**

That would be the source of your problem.
