### ISSUE TITLE
Add support for ProjectE

### ISSUE THREAD

**Issue by Mordenkainen** [Mordenkainen/EquivalentEnergistics#2]
Add support for autocrafting with ProjectE EMC.

**Comment by sinkillerj** [comment]
If you need any API calls that we lack stop by and let us know or open a pull: https://github.com/sinkillerj/ProjectE/

Someone mentioned your mod on my AMA and all I have to say is keep up the good work, you dont know how often people nag me for a mod like this lol.

**Comment by Mordenkainen** [comment]
Thanks! Its interesting to know that after only a few days of being released, word of this came around to you!

My current plan is to build in some basic "hackish" support for ProjectE for this weekend, and then perhaps spend a little time contributing to ProjectE with some API enhancements.

**Comment by sinkillerj** [comment]
Yea I saw how new the mod was and was a tad surprised. Let me know when you are happy with the addon and ill give it a feature in the ProjectE mod topic, great to see a addon being developed beyond the two from Japan.

**Comment by Mordenkainen** [comment]
One of the biggest issues I ran into with interacting with ProjectE was when I looked at your repository I saw the change to how you are storing the researched transmutations. If I understand the changes, a players transmutation data will be part of their player data and as such will only be available if the player is online and you have a reference to their EntityPlayer. This is a real issue for Equivalent Energistics. I have put a workaround into place for the time being, but it may be something you want to address.

I personally have always been hesitant to embed much data in the players file. I would always prefer to have an admin delete a mod specific data file for the player than have to delete the whole player if something saves wrong.

**Comment by williewillus** [comment]
yeah, I was thinking about that too when I saw this.
I'm currently trying out some things regarding improving (remaking) the API, and along with that some way to query the knowledge of offline players.
Hopefully I'll have it done soon
