### ISSUE TITLE
Error in onTick with invalid state

### ISSUE THREAD

**Issue by Mordenkainen** [Mordenkainen/EquivalentEnergistics#20]
It appears the Assembler can sometimes get into a state where it thinks it's crafting, but has no output items set. This can cause a NullPointerException.

http://openeye.openmods.info/crashes/40a5adda6ab353f030326de501192c73
http://openeye.openmods.info/crashes/1030b944bd1f1aa9ead1c59862283921

Change [tileCrafter.java line # 194] (https://github.com/Mordenkainen/EquivalentEnergistics/blob/master/src/main/java/com/mordenkainen/equivalentenergistics/tiles/TileEMCCrafter.java#L194) to sanity check the output item before trying to access it.

**Comment by desagas** [comment]
Here is an additional pastebin link to provide more information on this crash happening in my world as well, making it complete unusable. I am invested in seeing this fixed as a lot of work has gone into my world. I can not load it without it freezing and crashing.

http://pastebin.com/YED1LB88

**Comment by Mordenkainen** [comment]
If the issue is critical, remove Equivalent Energistics and reload your world. This will remove all EE items and blocks and make the error go away. Otherwise it may be a week or more before I have 0.3 with the fix for that bug ready.

**Comment by desagas** [comment]
I have mcedited the blocks out of the world as to not removed all my emc and crystals. I only posted because it was still listed as open and sometimes more reports are useful, and I figured any additional information may help. Thanks!

**Comment by Mordenkainen** [comment]
Glad you got your world running. I do not usually tell people to use MCEdit as people unfamiliar with it tend to do more harm then good!
