### ISSUE TITLE
Items being "eaten" by condensor when EMC is too high

### ISSUE THREAD

**Issue by utoc** [Mordenkainen/EquivalentEnergistics#22]
Greetings,

I have learned the items from ExU Septuple and Octuple compressed cobble (4.7 mil and 43mil EMC respectively).  After placing them in the hopper into the condenser, I receive no crystals in my AE system.  Sextuple (531K EMC) and lower seem to work fine though.

If you need a screenshot, let me know, I will be glad to provide a picture of the setup.

I'm running EE 507, Equiv Energistics 0.2 with FML 1448.  Modlist here:  https://www.reddit.com/r/BBQSauce/wiki/modlistrev1_0

**Comment by Mordenkainen** [comment]
Are you sure your network has enough power to handle the Octuple compressed cobble?

It costs 430,000 AE to process an Octuple cobble. This amount of AE must be available all at once, it will not be taken over time.

**Comment by utoc** [comment]
Bingo!  Thank you for explaining that mechanic.  I threw a few AE energy cells on the network and it processed it.  Would you consider making a change somewhere so that if there isn't enough power to process an item that it will import it into the ME system as an item rather than "eat" it?  Maybe a config option?  Or some visual indicator that something has gone wrong?  I will pass this onto my users, thank you!

**Comment by Mordenkainen** [comment]
It's not actually eating the item. It's still there in a buffer in the condenser, waiting for enough power to be processed. The condenser can hold 4 stacks.

**Comment by utoc** [comment]
Neat!

One more question.  Suppose I have 4 crystals (1024 EMC total) in my system and I go craft a TNT (964 EMC).  What happens with the leftover EMC?

**Comment by Mordenkainen** [comment]
It is held in the Assembler until enough leftover EMC has been collected (256 by default), and then it creates an EMC Crystal and inserts it into the AE system.

**Comment by utoc** [comment]
Thank you again.  I will try to find real issues and report them next time :)
