### ISSUE TITLE
Unable to craft items that need dense or super dense crystals

### ISSUE THREAD

**Issue by utoc** [Mordenkainen/EquivalentEnergistics#23]
I have aproximately 48K crystals (12.5M EMC worth) in my AE system, trying to craft a Septuple Compressed Cobble (4.7 Mil) and I am unable to.  It appears that all items that "cost" more than a dense EMC crystal (147K EMC) are unable to use regular crystals.  I am unable to craft dense EMC crystals even though I have learned them in my Tome

Here are some screenshots to help in case my explanation has fallen short: https://imgur.com/a/I4AZT

I'm running EE 507, Equiv Energistics 0.2 with FML 1448.  Modlist here:  https://www.reddit.com/r/BBQSauce/wiki/modlistrev1_0

**Comment by Mordenkainen** [comment]
So:
1. Don't learn the dense or super dense crystals.There is never any reason to craft those, they will be crafted by your system automatically as needed.

2. Can your AE system craft the Dense crystals directly?

**Comment by utoc** [comment]
After setting EE to unlearn the recipe, I am able to craft dense crystals.  I'll try to see if I can find a way to make them unlearnable yet still have an energy value so that users don't go doing the same thing I did.

Thank you.. again ;)

**Comment by Mordenkainen** [comment]
I will see if I can fix that in the mod itself as well.
