### ISSUE TITLE
Gem of Eternal Density

### ISSUE THREAD

**Issue by jusitnboggs** [Mordenkainen/EquivalentEnergistics#40]
Would it be possible for you to make us something like Gem of Eternal Density so we can get Cobble/Netherrack turned into iron then gold then diamonds and maybe then diamond blocks etc
to save space when we go on big mining trips ?

**Comment by MaPePeR** [comment]
ProjectE has you covered

**Comment by jusitnboggs** [comment]
I know that but I use EE3

**Comment by djozoku** [comment]
yes you can,i've done it

**Comment by Mordenkainen** [comment]
Lets leave this type of thing to another mod.
