### ISSUE TITLE
Can't craft items with damage values if the item with damage value 0 does not have an EMC value.

### ISSUE THREAD

**Issue by jozefjan** [Mordenkainen/EquivalentEnergistics#41]
I can pull the ingots from the table/tablet, but i can't craft them.

ProjectE-1.7.10-PE1.9.2
EquivalentEnergistics - 0.6 - 1.7.10
Mekanism-1.7.10-8.1.7.252

**Comment by Mordenkainen** [comment]
Do Osmium and Bronze ingots use metadata/damage values?

**Comment by jozefjan** [comment]
Yes they have damage values (i think), Osmium item id is 4633:1 if that helps.

**Comment by Mordenkainen** [comment]
Ok thanks. Several people have reported a similar issue. I am not yet sure of the cause and I am still investigating it.

**Comment by tecnobrat** [comment]
Any update on this? I can confirm that none of the Thermal Expansion ingots show up.

I have a theory (which I tested and confirmed).  The TE ingots are all of the same ID with different meta data.  The item which has a meta data of 0 has no EMC.  Other meta / damage values DO have EMC.

I added an EMC value to the TE metadata 0 item:

```
S:ThermalFoundation:material
M:0
E:1
```

And now ALL of the OTHER TE ingots show up.

I am playing project Ozone, where you can reproduce this issue.

**Comment by Mordenkainen** [comment]
Well now, that is very helpful!

At least we can provide a workaround for the issue.

If that is all it takes to recreate i will make sure the new version handles this case properly.

**Comment by tecnobrat** [comment]
@Mordenkainen its pulverized iron dust

**Comment by Mordenkainen** [comment]
Think I finally found the source of this issue. There appears to be an issue with the ProjectE API when dealing with items that use damage values. I have created sinkillerj/ProjectE#1222 with ProjectE to see if it can be resolved on their side.

In the mean time I will try to come up with a workaround.

**Comment by addrever** [comment]
Does this mean that a valid workaround would be if I assign, in the case of thaumium ingots, a value to alumentum?  I tried that and still do not see thaumium ingots.  I am using the latest build of projecte and equivalent energistics.

**Comment by Mordenkainen** [comment]
If Alumentum is thew item with damage value 0, then yes it should fix the issue.
