### ISSUE TITLE
Can't Craft Certain Items

### ISSUE THREAD

**Issue by cj89898** [Mordenkainen/EquivalentEnergistics#45]
I could craft anything from my tablet yesterday in my AE system, but today I got on my server and certain things are missing. I can't craft cake, TNT, and a lot of other things. The TNT is being exported (and crafted) aswell as cake. Not sure if this caused any issue.

**Comment by Mordenkainen** [comment]
Others have reported issues with itema disappearing, but this is the first for vanilla items without metadata like tnt or cake.

Have you made any changes? What new items have you researched recently?

**Comment by cj89898** [comment]
Sorry about the new issue, wasn't sure if it was the same thing because the other post I saw was only two items. The mods I have installed are here: http://pastebin.com/nH8gDy8k

The change I recently made was adding EMC to a few items (via EE3 Helper).

**Comment by Mordenkainen** [comment]
do you know what items you altered the emc values for just prior to the problem showing up?

**Comment by cj89898** [comment]
Specifically two items.

- Electrum Ingot
- Cryotheum Dust

I did Cryotheum Dust last night then hopped off. I got on today and added electrum, I'm not sure when it broke.

**Comment by Mordenkainen** [comment]
I am unable to recreate this. I am closing the issue, if it happens again please reopen it or open a new issue.
