### ISSUE TITLE
crafting calculates the emc value not correct

### ISSUE THREAD

**Issue by Kenshij** [Mordenkainen/EquivalentEnergistics#46]
Hi,

when i craft an item under 256 emc it eats the 256-emc-crystal and crafts a number of item wich stack emc value are under 256.

Tested it in a clean installation(deleted all configs and starts over new world, mods on the end of the post)
build an ae network with ME Drive,64k storage cell, 64k crafting storage, insert two 256-emc-crystal, learn ash infused slab(emc=1) and torch(emc=9)

a. craft 1 slab, it set to 64 slabs and will eat 256-crystal => loose of 200emc
b. craft 1 torch, it sets to 28 torches and eats 256-crystal => loose of 4 emc
=> after both craftings, Condenser and Assembler stores 0 emc

Mod-List:
ID,Name,Version,Custom Container,Disableable,Dependencies
mcp,Minecraft Coder Pack,9.05,true,YES,[]
FML,Forge Mod Loader,7.10.99.99,true,NEVER,[]
Forge,Minecraft Forge,10.13.4.1558,true,NEVER,[]
appliedenergistics2-core,Applied Energistics 2 Core,rv3-alpha-9,true,NEVER,[]
CodeChickenCore,CodeChicken Core,1.0.7.47,true,NEVER,[]
NotEnoughItems,Not Enough Items,1.0.5.111,true,NEVER,"[CodeChickenCore@[1.0.7,)]"
appliedenergistics2,Applied Energistics 2,rv3-alpha-9,false,DEPENDENCIES,"[appliedenergistics2-core, Forge@[10.13.4.1448,)]"
creativecore,CreativeCore,1.3.14,false,RESTART,[]
EE3HELP,EE3 Helper,2.2a,false,RESTART,[]
endercore,EnderCore,1.7.10-0.2.0.31_beta,false,DEPENDENCIES,[ttCore]
EE3,Equivalent Exchange 3,0.3.507,false,RESTART,"[Forge@[10.13.3,)]"
equivalentenergistics,Equivalent Energistics,0.6,false,RESTART,"[appliedenergistics2, EE3, ProjectE]"
NEIAddons,NEI Addons,1.12.11.36,false,RESTART,[NotEnoughItems]
NEIAddons|Developer,NEI Addons: Developer Tools,1.12.11.36,false,RESTART,[NEIAddons]
NEIAddons|AppEng,NEI Addons: Applied Energistics 2,1.12.11.36,false,RESTART,"[NEIAddons, appliedenergistics2]"
NEIAddons|Botany,NEI Addons: Botany,1.12.11.36,false,RESTART,"[NEIAddons, Botany]"
NEIAddons|Forestry,NEI Addons: Forestry,1.12.11.36,false,RESTART,"[NEIAddons, Forestry]"
NEIAddons|CraftingTables,NEI Addons: Crafting Tables,1.12.11.36,false,RESTART,[NEIAddons]
NEIAddons|ExNihilo,NEI Addons: Ex Nihilo,1.12.11.36,false,RESTART,[exnihilo]
neiintegration,NEI Integration,1.0.12,false,RESTART,"[Forestry@[3.6.0,)]"
neresources,Not Enough Resources,0.1.0.106,false,RESTART,"[NotEnoughItems, CoFHCore]"
ResourceLoader,Resource Loader,1.2,false,RESTART,[]
Waila,Waila,1.5.10,false,DEPENDENCIES,"[NotEnoughItems@[1.0.4.0,)]"
WailaHarvestability,Waila Harvestability,1.1.5,false,RESTART,"[TConstruct, ExtraTiC, TSteelworks, Mariculture]"
wailaplugins,WAILA Plugins,MC1.7.10-0.2.0-23,false,RESTART,"[Forge@[10.13.0.1208,), endercore@[1.7.10-0.0.1.10_alpha,), Waila]"
wawla,What Are We Looking At,1.3.1,false,RESTART,[Waila]
zcraftingmanager,Crafting Manager,1.1.0,false,RESTART,[]
zcraftingmanagercore,Crafting Manager Core,1.1.0,true,NEVER,[]

**Comment by Mordenkainen** [comment]
Given the situation you describe, if you craft 1 more slab, does an EMC Crystal get inserted back into your AE network as well?

Also, for your first example 256 - (1 * 64) = 192

For example, craft 1 slab, get 64 slabs, 1 EMC Crystal should be consumed (192 EMC should be stored in assembler)
Carft a 1 slab, get 64 slab + 1 EMC Crystal (128 EMC should be stored in the assembler)

**Comment by Kenshij** [comment]
Craftet multiple times 64 slabs no crystal is added, the EMC Value shown in Waila are always 0.0 of the assembler.

**Comment by Mordenkainen** [comment]
I am unable to recreate this.

Following the instructions given:
insert 2 crystals
craft 1 ash infused slab -> crafts 64 -> Assembler contains 192 EMC
craft 1 torch -> crafts 28 -> Assembler contains 196 EMC

No EMC is lost in these cases.

I'm closing this issue for the time being, but if it repeats reopen it.

**Comment by ThatGamerBlue** [comment]
can confirm
