### ISSUE TITLE
EMC Condenser causing tick loop error

### ISSUE THREAD

**Issue by Noahboy007** [Mordenkainen/EquivalentEnergistics#48]
Hey, Ive updated to Applied Energistic Rv 3 Beta 1 and noticed that the EMC Condenser is causing a Tick loop error which is crashing my world on startup, here is the report - 
[crash-2015-12-27_17.13.39-server.txt](https://github.com/Mordenkainen/EquivalentEnergistics/files/72851/crash-2015-12-27_17.13.39-server.txt) 

Hope this can be fixed soon

This might be a helpful note, but this crash also happens when placing the tile in a new world not just loading an exisiting one

**Comment by Mordenkainen** [comment]
The mod is built for AE RV 2 stable.

It will probably support RV3 in the future, but not until it goes stable.

**Comment by Mordenkainen** [comment]
Closing as this is an RV3/API issue and should be fixed when RV3 support is added.
