### ISSUE TITLE
 Problem with Channel

### ISSUE THREAD

**Issue by Louis-9902** [Mordenkainen/EquivalentEnergistics#49]
Hello,
I have turned off the channel in the AE options , and now the EMC Condenser produces  no crystals any more. Is it ab Bug or is there something I've made wrong?

**Comment by Mordenkainen** [comment]
I have never tried running without channels. When I get the chance I'll see if I can recreate this failure.

**Comment by Louis-9902** [comment]
Oh, that would be nice. :)

**Comment by Mordenkainen** [comment]
Closing as I am unable to recreate. Condenser appears to work fine with channels disabled.
