### ISSUE TITLE
Code License

### ISSUE THREAD

**Issue by beepbeat** [Mordenkainen/EquivalentEnergistics#6]
I just want to ask, if it is OK for you, if I take over some of your methods, for my own Implementation of AutoEMC-Crafting (I'm especially intertested int some of the EMCCafter methods).

**Comment by Mordenkainen** [comment]
Ok, I'm going to answer the question, but ultimately it won't answer your question.

I have not yet decided what license to apply to this code, so as is listed on Curse, it is currently "All Rights Reserved".

I am a firm believer in Open Source, so in the end I am sure that I will settle on a far more permissive license. In the mean time, feel free to look at my code for a "reference" if you wish to duplicate it's functionality.

That said, I spent a lot of time trying to find a feature to build a mod around that was often asked for, but that no one had ever provided. I did not just cobble together a mod with a bunch of re-hashes of things that had already been done, I wanted to do something fairly original. I can not stop you from duplicating the functionality of this mod, but I ask in good conscience that you give it a chance to live without a bunch of clones popping up all over the place. These mods have been out for quite a while without anyone doing what I have done, and less than a week later someone is asking if they can duplicate the functionality, that is very disheartening at best.

**Comment by beepbeat** [comment]
I didn't want to insult you, but I have also worked on the impleentation, then stumbled upon you and this mod, so I wanted to ask before taking your work without permissions. I can give your mod a chance, but  I also want my mod to live atleast unpublished for myself.

**Comment by Mordenkainen** [comment]
Nope, no insult taken, nor any intended.

Like I said, feel free to use my code as a reference. If you see things in it that don't make sense to you, feel free to ask.

I completely understand that I may not have been the first to start working on this, or to have the idea.

The only things I ask is that if you wish to duplicate this functionality in a public mod, please make it function differently enough that there is a big enough difference for people to be able to see a benefit in one mod vs. the other. If you are duplicating this functionality for a private mod... then have at it!
