### ISSUE TITLE
Proper Build Setup & AE2-RV3 changes

### ISSUE THREAD

**Issue by kojul** [Mordenkainen/EquivalentEnergistics#60]
I'm trying to build EquivalentEnergistics currently and unlike other mods that I've built from source, there's no packaged gradle or api/libs with the source, so I'm wondering what I need to add to a project to get it to build properly. Also, is there any better way to contact you via twitter or IRC or something?

Also, in order to get 0.6 working with RV-3, I'm 90% sure from what I could compile with adding the full jar of ae2 as a lib that the only issue is in TileEMCCondenser and TileEMCCrafter you call on gridProxy, which they set to private and added a getter of getProxy(), so changing all the gridProxy attribute to getProxy() should work, in theory.

**Comment by Mordenkainen** [comment]
The whole mod is being rewritten. The source for 0.6 was never commited to the repo. I would not bother even looking at trying to make the existing source compatible with RV3. Just wait forthe next release.

**Comment by kojul** [comment]
Thanks for the reply, do you have any kind of timeline or need any help finishing up the new version?

**Comment by Mordenkainen** [comment]
I expect it to be ready sometime around the end of the month.
