### ISSUE TITLE
RV3

### ISSUE THREAD

**Issue by ThatGamerBlue** [Mordenkainen/EquivalentEnergistics#61]
Crash with ae2 rv3 http://pastebin.com/2K9EZHmp

**Comment by Mordenkainen** [comment]
Closi ng as this has been reported many times and is not a bug. The mod currently does not support RV3.

**Comment by ThatGamerBlue** [comment]
> Supports AE2

^^ is a lie

**Comment by Mordenkainen** [comment]
Are you serious? RV3 is an alpha/beta.. I.E. not production software and not a "released" version in the parlance of the software industry. In terms of "supported versions" of a thing, it doesn't exist.
