### ISSUE TITLE
[1.7.10 - Equivalent Energistics 0.6 ] Some items missing from Alchemical Tome

### ISSUE THREAD

**Issue by addrever** [Mordenkainen/EquivalentEnergistics#62]
Not sure how to show you this, but if I add Thaumium to the Transmutation Tablet it shows up fine, but if I look in AE, it doesn't show up.  Is this by design?

**Comment by Mordenkainen** [comment]
Does Thaumium use damage values/metadata?

**Comment by addrever** [comment]
If I understand you correctly the ID for Thaumium in my instance is 4267:2

**Comment by Mordenkainen** [comment]
This is a known issue with items that use damage values.

I'm closing this as a duplicate of #41
