### ISSUE TITLE
[1.7.10 - Equivalent Energistics 0.6 ] Cannot craft when EMC Crystals are in  DSU

### ISSUE THREAD

**Issue by addrever** [Mordenkainen/EquivalentEnergistics#63]
Cannot craft items when EMC Crystals are in a deep storage unit.  storage bus is set to bi directional

**Comment by Mordenkainen** [comment]
The crafting system does not care where the crystals are stored. If the DSU isn't exposing the crystals properly, there isn't much I can do about it.

**Comment by addrever** [comment]
Thanks for the response!
