### ISSUE TITLE
Server and Client Crash every time I place a EMC Assembler

### ISSUE THREAD

**Issue by Rnrn13** [Mordenkainen/EquivalentEnergistics#64]
I'll give you my crash report (Client) and My crash report (Server)

http://pastebin.com/WKSTQGDD ( Crash Log for Client )

http://pastebin.com/TY0LyJYu ( Crash Log for Server )

**Comment by Mordenkainen** [comment]
This error is due to the use of AE2 RV3. This mod is not compatible with RV3 at this time. I hope to fis this in the next release.

**Comment by Rnrn13** [comment]
do you know when the Rv3 version will be out?

**Comment by Mordenkainen** [comment]
Hopefully soon but I have no ETA. Its a rewrite from scratch and I only have so much time to work on it.

**Comment by Rnrn13** [comment]
Ahh  ok thanks for responding ! :+1:

**Comment by Rnrn13** [comment]
Is there anytime frame on the mod being updated as of now?

**Comment by Mordenkainen** [comment]
Not at this time.

**Comment by Rnrn13** [comment]
Do you think you could comment in this thread or send me a message once the RV3 version is out?

**Comment by Mordenkainen** [comment]
I will post the new vwrsion to the forum thread when it is ready.
