### ISSUE TITLE
Dev version

### ISSUE THREAD

**Issue by tomet123** [Mordenkainen/EquivalentEnergistics#68]
Can you upload dev version of this mod to curse? I have using your DEV version 0.7 compiled from code. When I add modpack with your mod to curse. Modpack Will be rejected because you do not alowing in your licence to use dev version on modpacks. 

Sorry for my bad anglish. I am not from english speak state.

**Comment by Mordenkainen** [comment]
The dev version is incomplete and not fully functional. As such I will not upload it to Curse. Once it is ready, I will release it.
