### ISSUE TITLE
FTB Inventions

### ISSUE THREAD

**Issue by Snake2002** [Mordenkainen/EquivalentEnergistics#69]
I tried to add your mod to the ftb Inventions modpack. The game is starting normal, but when i connect one of the new blocks to my ME-System, the game crashes instantly. When i enter the world it crashes again. So i can only start the world again, when i disable the mod. Is this a known issue? I will try to add a crash log later.

**Comment by Mordenkainen** [comment]
I assume that FTB Inventions uses AE2 RV3?

Hopefully within the next week I will be releasing a new version that is compatible with RV3.
