### ISSUE TITLE
EMC Multiplication Without Energy Cell

### ISSUE THREAD

**Issue by Rayhawk11** [Mordenkainen/EquivalentEnergistics#70]
I compiled the v0.7 beta for usage on my server. It is being run alongside AE2 rv3 beta 6 and EE3 1.7.10 v0.3.0.547. 

If the ME network does not have an energy cell, the condenser multiplies the EMC of any item piped into it by an unknown factor. This resulted in a few stacks of 1 EMC leaves rapidly producing millions of EMC. Adding an energy cell to the ME network prevented this from happening.

AE2 is configured to have channels disabled. This may or may not be part of the problem.

**Comment by Mordenkainen** [comment]
Which commit did you compile and what tier of condenser were you using?

Also, how was the network powered if it did not have a cell? Have you also disabled AE's power usage?
