### ISSUE TITLE
Use AE2 Molecular Assembler and Crafting patterns

### ISSUE THREAD

**Issue by Ruhrpottpatriot** [Mordenkainen/EquivalentEnergistics#74]
For autocrafting you currently need an EqE version of the molecular assembler at different tiers. This adds  for the player and more code to maintain.

I propose to drop the EMC Assembler and move autocrafting to standard AR Molecular Assemblers.

Currently EMC is stored as crystals that can be taken out of the AE storage system. This means that they can be used in a Crafting Pattern, which is what I'm proposing.
The player would use the required crystals in a processing pattern and get the required amount of items at the end. Additional speed would be done by parallelization of molecular assemblers.

This would also allow the Alchemical tome to be removed from the game and also prevent the ME Crafting terminal to be cluttered with items a player doesn't want to craft, but at some point has learned them.

**Comment by Mordenkainen** [comment]
This can not be done as the AE assembler has no way to return fractional EMC back into the system.

If an item costs 0.5 EMC, the assembler will be sent a 1 EMC crystal. The remaining EMC would then be lost. This may seem minimal, but there are a lot of items with fractional EMC, and a large autocrafting system could lose a lot of EMC over time this way.

Some items have fractional EMC all the way down to 1000th an EMC. Trying to add crystals to support these cases would be too complex.

In the future the plan is to add a terminal that can be used to configure what items in the tome will be offered for crafting as well as other crafting related settings.

**Comment by MaPePeR** [comment]
Maybe you could add a fractional emc storage to the assembler so the emc is not lost forever, but maybe used on the next crafting operation?

**Comment by Ruhrpottpatriot** [comment]
I was thinking of making a `Fractional EMC Crystal` that stores leftover EMC after a crafting operation. The player usually would never see this crystal as it'd get automatically pushed back into the system and added back to the stored EMC. This should be possible by storing the leftover EMC in a property on the crystal itself, so you'd only have one crystal for every EMC value n < 1.

Of course the player would have to be able to pick this crystal up if the auto crafting spits the items into a chest and not back into the system. However the crystal would useless since it can't be used in any recipe.

**Comment by Mordenkainen** [comment]
The Molecular assembler never pushes anything back other than its output item.
