### ISSUE TITLE
not enough power for ultimate condenser and octuple compressed cobble

### ISSUE THREAD

**Issue by DoomSquirter** [Mordenkainen/EquivalentEnergistics#78]
running 0.7

so trying to input octuple compressed cobble into the ultimate condenser and it gets red particles and waila shows "not enough power" but I'm sort of confused.  how does it detect the 'power' available?  it's not as if as soon as I started, all my ae went down or anything.  Using a network tool shows 500rf max power but I guess I'm just not understanding where it's getting that number.  do I need to add energy cells to boost it or something?

btw, 0.7 rewrite?  +1  :)  definately like this way much better than previous.  pretty damn slick.

**Comment by DoomSquirter** [comment]
so I figured adding 50 dense energy cells might be the key but nope.  maybe some sort of additional info might be nice, like what power it has access to or the power needed, shown in waila?

**Comment by DoomSquirter** [comment]
ofc it's now when I wonder if it would have been better to just edit my first response but oh well lol

so I setup a crafter decrafting the octuple into septuple and then sextuple which I'm exporting out and it does seem to convert that tho as I watch my power dip as it processes the cobbles I notice that it's using the max power of the ae system but not my power draw.  I can push out 60M rf/t easy with what I'm connected with, so that's confused me a little.  At my estimate, I'd need like 500+ dense energy cells to handle octuple.  I noticed some config settings tho I wasn't 100% sure what the 'drain' per tier is.  

In addition, even tho it'll handle the sextuple, it's fluctuating between fine and particle effects where it says not enough power, but I'm using translocators so I can see the cobbles going in and it makes me wonder if some of this is getting voided, and if not, how big a buffer this thing can hold?  Maybe just some more visibility, like a gui or at very least, some additional waila info would do wonders to give a person an idea what they need to do to perform whatever function they are trying to do.

**Comment by Mordenkainen** [comment]
If using the default config, take the EMC value of the item and multiply by 0.1.

This is the amount of AE that item will cost to condense. If your network does not have that many AE stored, then you will bet the error you are seeing.

**Comment by DoomSquirter** [comment]
Can I get a clarification/verification of one thing tho?
Amount of AE is the 'power' rating that you see while using the network tool?  Only way to increase that seems to be adding the energy cells.  

I did learn something interesting tho since I've never had to deal with this much power draw on ae before.  I guess there's an upper limit of power going into the system from a single connection.  iirc it was around 5k rf.  so to actually push a huge amt of power I ran another set of controllers in a box under my room and ran cryo fluxducts from a tesseract all along them to majorly increase my power draw into ae.  even doing that tho with like 30+ connections it still isn't enough to handle the octuple.  just down-crafting them now.

Feel free to close this question.  thanks so much for answering it.  Happy belated new year :)

**Comment by Mordenkainen** [comment]
Sorry about the delay in getting back to you.... Yes the amount of AE is the number you see in the network tool (assuming you have it set to show AE instead of some other power type).

And yes, the only way to increase that number is with Energy Cells.

As far as limitations to the amount of power a system can import, I'm not sure. That is more of a core AE thing.
