### ISSUE TITLE
Terminal removal system for items with EMC

### ISSUE THREAD

**Issue by Anyone700** [Mordenkainen/EquivalentEnergistics#81]
It is REALLY inconvenient to find a needle (an item with EMC) accidentally thrown into a massive haystack (A terminal with over 300+ items) with an automated system.

I know I could manually search EMC, and it would show all items with EMC in the terminal. However, this may not be obvious to new users, and it would be awesome to have a system to do this chore automatically

**Comment by Mordenkainen** [comment]
Do what chore? Identify items with EMC that you have stored in your ME system?

Unfortunately, that would require completely replacing the standard ME terminals (crafting, normal, and pattern) or adding a new terminal for this purpose.

That is something beyond the scope of this mod.

I have thought about adding a way to sort items based on EMC, but haven't for a couple of reasons:
- There are already mods that do this.
- It requires low level patching of the AE code to accomplish.

I may at some point try to make a PR for adding this type of capability to AE, but have not had the time.
