### ISSUE TITLE
Recipe player-data erased

### ISSUE THREAD

**Issue by Anyone700** [Mordenkainen/EquivalentEnergistics#83]
I was right-clicked in a transmutation tablet and my cat sat on my keyboard. Now all the recipes that were known by all the players in my world have been wiped. I was using the latest stable version of project E. Thankfully I manually backup my world. I only lost 2 days worth of recipes and 0 days of in-game progress

**Comment by Mordenkainen** [comment]
There is nothing within Equivalent Energistics that can cause Project E to forget a transmutation. It reads the transmutation list, it never writes to it.

I suspect that this is something that should be reported to the Project E team.
