### ISSUE TITLE
Machine for copying items without emc.

### ISSUE THREAD

**Issue by Gluptak** [Mordenkainen/EquivalentEnergistics#84]
The machine that is on the site copies items without emc. This happens when the item is inserted without emc to the hopper. Screenshot https://imgur.com/a/agNmT

**Comment by Mordenkainen** [comment]
What version of Equivalent Energistics?

**Comment by Gluptak** [comment]
EquivalentEnergistics - 0.7 - 1.7.10

**Comment by Mordenkainen** [comment]
What tier condenser and is it configured to automatically import or eject to the hopper?

**Comment by Gluptak** [comment]
Is set to green and works on all configurable

**Comment by Mordenkainen** [comment]
Thanks, I found the source of the issue and it should be resolved in the next version.

**Comment by Mordenkainen** [comment]
Lets keep this open until the fix makes it in for tracking purposes.

**Comment by Mordenkainen** [comment]
Fixed in 0.8
