### ISSUE TITLE
[1.12.2] EMC Condensers Dupe Items Without EMC From Modden Inventories

### ISSUE THREAD

**Issue by TheLimePixel** [Mordenkainen/EquivalentEnergistics#96]
This person better explained it: https://github.com/EmosewaPixel/Modern-Skyblock-3/issues/437 (for reference, the Roost is from the Roost mod, the Iron Freezer is from Sky Resources)

**Comment by Mordenkainen** [comment]
What tier of condenser?

Is the side of the condenser facing the inventory configured for input, output, or unconfigured?

Do these inventories have auto-eject/import functionality? If so, how is it configured?

**Comment by TheLimePixel** [comment]
I tried with the Ultimate Condenser, configured to input.. Those machines don't auto-output, but can have items output from them.

**Comment by Mordenkainen** [comment]
Need to check this in 1.10 as well.

**Comment by Mordenkainen** [comment]
Yup, this affects 1.10 as well.
