### ISSUE TITLE
hopper on condenser makes a crash/unplayable world

### ISSUE THREAD

**Issue by tindin** [Mordenkainen/EquivalentEnergistics#97]
hooking a hopper up to a condenser to pipe items in crashes the world and causes the world to crash ever login.
[crash-2018-07-06_16.52.54-server.txt](https://github.com/Mordenkainen/EquivalentEnergistics/files/2172254/crash-2018-07-06_16.52.54-server.txt)

**Comment by Mordenkainen** [comment]
Have you tried disabling FoamFix?

**Comment by Mordenkainen** [comment]
Actually, this appears to be due to an update in PE. See Issue #98 

Downgrade PE or wait for a fix.... It might be some time for the fix since I'm not sure how I will deal with this change from the PE side.

Closing this in favor of #98
