### ISSUE TITLE
Crash due to PE changing from doubles to longs in the API.

### ISSUE THREAD

**Issue by DustRaven** [Mordenkainen/EquivalentEnergistics#98]
The latest version of ProjectE hast changed the return value of getValue() to long. The game crashes when you try to place the Assembler.

-> https://github.com/sinkillerj/ProjectE/issues/1718

https://github.com/Mordenkainen/EquivalentEnergistics/blob/4bae29d82dd71e530ef6c30e49f0ad5c7ebebb1e/src/main/java/com/mordenkainen/equivalentenergistics/integration/ae2/EMCCraftingPattern.java#L108

log: https://gist.github.com/DustRaven/654e608d130746465a074267ae260f9a

**Comment by Mordenkainen** [comment]
Need to look in to how to fix this. Don't really want to have to maintain a "pre change" and "post change" version for the 2 diff APIs.... HMMMMMM.

**Comment by MaPePeR** [comment]
I think the right way is to set a minimum version requirement for ProjectE and just maintain post change...

**Comment by tomtenberge** [comment]
i agree with @MaPePeR on this one, its not like they are going to revert it any time soon

**Comment by ghost** [comment]
I would say it's best to move forward and have a pre-change version that isn't updated, and a post change one that is. I'd be glad to have 64 bit support for properly displaying the stack EMC when it goes over the 32 bit limit (yes, I know, that's a lot of EMC, but with compressed cobblestone and emerald chickens it's not exactly unrealistic).

**Comment by MaPePeR** [comment]
@DemonfangArun That doesn't work, because EquivalentEnergistics is compatible to older versions of MC, but ProjectE is not, so the int->long change is not in older MC versions of ProjectE.
